#:schema https://mago.carthage.software/1.26.0/schema.json
# Welcome to Mago!
# For full documentation, see https://mago.carthage.software/tools/overview
version = "1"
php-version = "8.5.0"

[source]
workspace = "."
paths = ["bin/", "src/", "tests/"]
includes = ["vendor"]
excludes = []

[source.glob]
literal-separator = true

[formatter]
preset = "default"
always-break-named-arguments-list = true
always-break-attribute-named-argument-lists = true

[linter]
integrations = ["symfony", "pest"]

[linter.rules]
literal-named-argument = { enabled = false }
tagged-todo = { enabled = false }
no-boolean-flag-parameter = { enabled = false }

# https://mago.carthage.software/tools/analyzer/configuration-reference#strict-mode
[analyzer]
find-unused-expressions = true
find-unused-definitions = true
find-overly-wide-return-types = true
analyze-dead-code = true
check-throws = false # Do not check for missing @throws annotations.
check-missing-override = true
find-unused-parameters = true
check-missing-type-hints = true
check-closure-missing-type-hints = true
check-arrow-function-missing-type-hints = false # Do not require type hints for arrow functions.
enforce-class-finality = false # Do not require classes to be final.
require-api-or-internal = false # Do not require @api nor or @internal annotations.
check-experimental = true

strict-array-index-existence = true
no-boolean-literal-comparison = true

trust-existence-checks = false
