name: Set Envs

runs:
  using: composite
  steps:
    - run: echo OS=Linux >> $GITHUB_ENV
      if: runner.os == 'Linux'
      shell: bash
    - run: echo OS=Darwin >> $GITHUB_ENV
      if: runner.os == 'macOS'
      shell: bash
    - run: |
        echo "::error title=Unable to determine OS::Unexpected runner.os '${RUNNER_OS}'"
        exit 1
      if: env.OS == ''
      env:
        RUNNER_OS: ${{ runner.os }}
      shell: bash

    - run: echo ARCH=arm64 >> $GITHUB_ENV
      if: runner.arch == 'ARM64'
      shell: bash
    - run: echo ARCH=amd64 >> $GITHUB_ENV
      if: runner.arch == 'X64'
      shell: bash
    - run: |
        echo "::error title=Unable to determine ARCH::Unexpected runner.arch '${RUNNER_ARCH}'"
        exit 1
      if: env.ARCH == ''
      env:
        RUNNER_ARCH: ${{ runner.arch }}
      shell: bash
